"""make team lead_id nullable

Revision ID: 38d5ded3367e
Revises: 49f0d6fa517f
Create Date: 2026-04-07 14:33:35.376525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d5ded3367e'
down_revision = '49f0d6fa517f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
